### ISSUE TITLE
Confirmed - Not working anymore in version 22.5

### ISSUE THREAD

**Issue by jdb130496** [NGLEmp/NGLEmp#10] opened 2021-08-19 05:07 UTC
Confirmed - Not working in version 22.5. Please look into.

**Comment by artquest** [comment] 2021-08-19 18:24
Same here. Can it be because of the plugin is packed? There've been a case lately with packed versions of the Astute plugins for latest Illustrator.

**Comment by upiter** [comment] 2021-08-19 18:42
Duplicate of "Does not work with version 22.5" #9

**Closed** 2021-08-19 18:50 UTC
